_type_: dreamer

enabled: false
anomaly_based_falling_asleep:
  anomaly_threshold: .6
  alpha: .8
  beta: 2.
  max_prob: .15

prediction_depth: 18
n_prediction_rollouts: [3, 12]

sa_encoder:
  clusters_similarity_threshold: .7

reward_model:
  learning_rate: [1., 1.]

anomaly_model:
  learning_rate: [.1, 1.]

transition_model:
  tm:
    cells_per_column: 1
    initial_permanence: .3
    connected_permanence: .3
    activation_threshold: .88
    learning_threshold: .8
    max_new_synapse_count: 1.0
    max_synapses_per_segment: 1.0
    predictedSegmentDecrement: .001
    permanenceIncrement: .05
    permanenceDecrement: .01
    maxSegmentsPerCell: 8
